bugfixes
DagsHub/client pull request #184
Opened 2022-10-02 06:47 UTC by jinensetpal

2022-10-02 09:41 UTC, simonlsk requested changes
Hey, looks good but it looks like you have formatting issues. 
Parts of the diff seem to just have extra indentations that shouldn't be there.

2022-10-02 09:42 UTC, simonlsk commented on dagshub/streaming/filesystem.py
> +                        self._mkdirs(path, dir_fd=self.project_root_fd)
Isn't it breaking patching?

2022-10-02 14:34 UTC, kbolashev commented on dagshub/streaming/filesystem.py
> +            response = self._api_listdir('')
I tried to see if private repos work now, and I'm crashing here now.
Seems like the result of this is cached after line 120 and it doesn't retry to access the folder again

2022-10-21 06:45 UTC, jinensetpal commented
branch is now irrelevant

2022-10-21 06:45 UTC, closed without merging