Use the last revision of the branch's remote on API requests
DagsHub/client pull request #193
Opened 2022-10-11 12:03 UTC by kbolashev

Now on each API request the client is opening two files:
- .git/HEAD to see what branch/revision we're on
- the HEAD of the remote for the associated branch

I'm not sure if trying to do some logic around caching them is a good idea

2022-10-13 13:43 UTC, simonlsk requested changes

2022-10-13 13:43 UTC, simonlsk commented on dagshub/streaming/filesystem.py
> +        for branch, branch_section in [(b, git_config[b]) for b in git_config if b.startswith("branch ")]:
not relevant anymore

2022-10-13 13:51 UTC, kbolashev commented on dagshub/streaming/filesystem.py
> +    fs.install_hooks()
Local debugging. So I can install_hooks on a repo by providing a path to it in argv.

2022-10-16 07:06 UTC, simonlsk approved these changes

2022-10-16 07:06 UTC, simonlsk commented
Linter is not passing.

2022-10-16 07:07 UTC, kbolashev commented
Oops, sorry for that and thanks for noticing

2022-10-16 07:12 UTC, merged