Feature/create dataset repo
DagsHub/client pull request #230
Opened 2022-11-06 14:06 UTC by martintali

2022-11-07 14:23 UTC, deanp70 requested changes
Aside from the Docstring comments. There are 2 additional important things:
1. Fixing the issue we discussed on [Discord](https://discord.com/channels/696726028751732806/715453975104585738/1039178664669085767) both in `create_dataset` and `create_repo`
2. We should update [our docs](https://dagshub.com/docs/feature_guide/direct_data_access/#creating-a-dataset-repo-from-scratch-with-python)

2022-11-13 16:50 UTC, kbolashev approved these changes
LGTM

2022-11-13 16:56 UTC, deanp70 approved these changes

2022-11-13 16:57 UTC, kbolashev approved these changes
👍

2022-11-13 17:19 UTC, merged