generate and save Cpermanent token after going through oauth
DagsHub/client pull request #357
Opened 2023-09-18 05:34 UTC by simonlsk

Provided OAuth token sometimes ends in the middle of training, then starts throwing 401’s. This happens also for users that use local notebooks, where they work intermittently.

### Proposed solution
After oauth token is triggered, set a permanent token for the user using the token API, unless specified otherwise.

2023-09-18 06:57 UTC, kbolashev approved these changes
:(

2023-09-18 07:06 UTC, kbolashev requested changes

2023-09-18 07:06 UTC, kbolashev commented on dagshub/auth/tokens.py
> +    token_data = {"name": CLIENT_TOKEN_NAME}
Add a date in there or something like that

2023-09-18 07:06 UTC, kbolashev commented on dagshub/auth/tokens.py
> +    perm = _generate_permanent_token(token)
Check that `token` is of type `OAuthDagshubToken`, that should be enough
Alternatively add an `is_expirable()` onto the Token ABC, but that's probably overkill

2023-09-18 07:06 UTC, kbolashev commented on dagshub/auth/tokens.py
>              return good_token
Forgot to implement?

2023-09-26 06:39 UTC, simonlsk commented
Oauth slider in the redemption screen will let users select how long the token should last. PR no longer necessary.

2023-09-26 06:39 UTC, closed without merging