Add a --bucket flag to dagshub download cli
DagsHub/client pull request #452
Opened 2024-03-25 09:33 UTC by kbolashev

Keeping things consistent with `dagshub upload`, after adding a `--bucket` flag there, the `dagshub download` function is now inconsistent and downloading a file from the bucket requires knowing the name of the repo, so:
```
dagshub download user/repo s3:/repo/data data
```

After this PR the behavior with the upload is preserved, so same command can be done like this:
```
dagshub download --bucket user/repo data data
```

Also ran ruff formatter, so apologies for the reformat

2024-03-25 09:41 UTC, kbolashev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a --bucket flag to `dagshub download`](https://trello.com/c/fk520Psk/1976-add-a-bucket-flag-to-dagshub-download)

2024-03-31 13:50 UTC, guysmoilov requested changes

2024-03-31 13:50 UTC, guysmoilov commented on dagshub/common/cli.py
> +    help="Download the file(s) to the repo's DagsHub Storage bucket. "
A link to docs would be nice if possible
```suggestion
    help="Download the file(s) from the repo's DagsHub Storage bucket. "
```

2024-03-31 13:50 UTC, guysmoilov commented on dagshub/common/cli.py
> +    help="Upload the file(s) to the repo's DagsHub Storage bucket (s3-compatible)",
A link to docs would be nice if possible

2024-03-31 14:40 UTC, guysmoilov approved these changes

2024-03-31 15:00 UTC, merged