LS API Integrations
DagsHub/client pull request #573
Opened 2024-12-31 16:22 UTC by jinensetpal

- Added function to get LS Client
- Added repoApi functions to directly interact with LS instance for a given project
- Migrated LS calls to repoAPI from auto-labelling integration

2025-01-05 09:00 UTC, kbolashev requested changes

2025-01-06 13:46 UTC, jinensetpal commented on dagshub/common/api/repo.py
> +        )
Currently, what I'm doing is any 2XX (success) request is fine, and the rest raise exceptions: https://github.com/DagsHub/client/blob/247f640b1ede960a0dcfe54124683a5385313272/dagshub/common/api/repo.py#L80-L81

Do you want me to check specifically for 200/201? I think being generic makes sense here.

2025-01-06 13:48 UTC, kbolashev commented on dagshub/common/api/repo.py
> +        )
Sorry, disregard this one, I actually wrote it before I noticed that it's behind a tenacious check. 
This is fine as is 👍

2025-01-06 14:51 UTC, jinensetpal commented on dagshub/repo_bucket.py
> +    return LabelStudio(**kwargs)
For 3, I presume folks would want to use the legacy client even with newer versions, imo the legacy API is more intuitive / if they don't want to update function calls just yet. I think it's better to keep it user defined with non-legacy by default. Thoughts?

2025-01-06 15:50 UTC, kbolashev commented on dagshub/repo_bucket.py
> +    return LabelStudio(**kwargs)
I'm not familiar enough with the SDK, but this is a choice that I as a user don't want to make.
If I'm going to Label Studio's website and they talk about their "new" client, and getting a "legacy" one is more annoying, it's probably not that valuable for me. Most of the docs are going to be about the new client I assume.

Mark the function as experimental, that way I won't feel bad about dropping it sometime later.

This whole flow should be very cleanly explained in the docs, with links to LS's docs pointing at which client you're going to be getting for each of this kwarg values

2025-01-06 15:52 UTC, kbolashev commented on docs/source/reference/metric_logging.rst
Don't delete, this is deprecated but I explicitly didn't delete it for now (it's commented out in the index)

2025-01-06 15:56 UTC, kbolashev commented on dagshub/repo_bucket.py
> +    return LabelStudio(**kwargs)
Link for the old client: https://labelstud.io/sdk/client.html
Link for the new client (best match, actually couldn't find a good enough one): https://api.labelstud.io/api-reference/introduction/getting-started

2025-01-06 16:53 UTC, jinensetpal commented on docs/source/reference/metric_logging.rst
Gotcha

2025-01-07 08:25 UTC, kbolashev approved these changes
Looks great, ty!

2025-01-07 08:32 UTC, merged